# Generated by Django 2.1 on 2018-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_mail', models.CharField(max_length=100)),
                ('_number', models.IntegerField(default=10)),
            ],
        ),
    ]
